<a href="https://colab.research.google.com/github/fyse-nassar/Machine-Learning-Lab-Assignments/blob/master/pca_svm_glass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import Normalizer
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import decomposition







In [0]:
data = pd.read_csv("glass.csv")

X = data.drop(columns = "Type")
Y = data.iloc[:,-1:]

#Check existence of NAN values
#data.isnull().sum()



In [0]:
#Splitting data
xTrain, xTest, yTrain, yTest = train_test_split(X, Y, test_size = 0.2, random_state = 33)




In [0]:
# Normalizing the training data and storing the transformation parameter 'scalar' to be applied on test data
scaler = Normalizer().fit(xTrain)
xTrain = scaler.transform(xTrain)
xTest = scaler.transform(xTest)




In [29]:
# SVM without PCA using RBF Kernel

svclassifier = SVC(kernel='rbf', gamma='scale')
svclassifier.fit(xTrain, yTrain)
yPred = svclassifier.predict(xTest)





/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [30]:
print(confusion_matrix(yTest,yPred))
print(classification_report(yTest,yPred))

score1 = accuracy_score(yTest,yPred)
print("Your Model Accuracy is", score1)

[[ 0 10  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  8  0  0  0  0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        10
           2       0.35      1.00      0.52        15
           3       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         8

    accuracy                           0.35        43
   macro avg       0.06      0.17      0.09        43
weighted avg       0.12      0.35      0.18        43

Your Model Accuracy is 0.3488372093023256


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [31]:

xTrain, xTest, yTrain, yTest = train_test_split(X, Y, test_size = 0.2, random_state = 33)

pca = decomposition.PCA(n_components=3)
xTrain = pca.fit_transform(xTrain)
xTest = pca.transform(xTest)

scaler = Normalizer().fit(xTrain)
xTrain = scaler.transform(xTrain)
xTest = scaler.transform(xTest)


svclassifier = SVC(kernel='rbf', gamma='scale')
svclassifier.fit(xTrain, yTrain)
yPred = svclassifier.predict(xTest)


score1 = accuracy_score(yTest,yPred)
print("Your Model Accuracy is", score1)

print(confusion_matrix(yTest,yPred))
print(classification_report(yTest,yPred))

Your Model Accuracy is 0.5813953488372093
[[ 8  2  0  0  0  0]
 [ 5 10  0  0  0  0]
 [ 4  0  0  0  0  0]
 [ 0  3  0  0  0  1]
 [ 0  2  0  0  0  0]
 [ 1  0  0  0  0  7]]
              precision    recall  f1-score   support

           1       0.44      0.80      0.57        10
           2       0.59      0.67      0.62        15
           3       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.88      0.88      0.88         8

    accuracy                           0.58        43
   macro avg       0.32      0.39      0.35        43
weighted avg       0.47      0.58      0.51        43



/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
